version: "3.8"

services:
  fastapi_app:
    image: python:3.9-slim
    container_name: Stash-Tracker-Discord-Bot
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "
        pip install --no-cache-dir -r requirements.txt &&
        python bot.py
      "
    environment:
      - PYTHONUNBUFFERED=1